# Generated by Django 5.0.7 on 2024-08-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее изменение урока"
            ),
        ),
    ]
